---
name: jmx4perl
version: 0.15_1
author:
  - Roland Huss (roland@cpan.org)
abstract: Easy JMX access to Java Applications
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
requires:
  Carp: 0
  Data::Dumper: 0
  Getopt::Long: 0
  JSON: 2.12
  LWP::UserAgent: 0
  Module::Find: 0
  Object::Tiny: 1.06
  Pod::Usage: 0
  Scalar::Util: 0
build_requires:
  Module::Build: 0
  Test: 0
  Test::More: 0
recommends:
  Nagios::Plugin: 0.27
provides:
  JMX::Jmx4Perl:
    file: lib/JMX/Jmx4Perl.pm
    version: 0.15_1
  JMX::Jmx4Perl::Agent:
    file: lib/JMX/Jmx4Perl/Agent.pm
    version: 0
  JMX::Jmx4Perl::Agent::UserAgent:
    file: lib/JMX/Jmx4Perl/Agent/UserAgent.pm
  JMX::Jmx4Perl::Alias:
    file: lib/JMX/Jmx4Perl/Alias.pm
  JMX::Jmx4Perl::Alias::Object:
    file: lib/JMX/Jmx4Perl/Alias.pm
  JMX::Jmx4Perl::ProductHandler::BaseHandler:
    file: lib/JMX/Jmx4Perl/ProductHandler/BaseHandler.pm
  JMX::Jmx4Perl::ProductHandler::JBoss:
    file: lib/JMX/Jmx4Perl/ProductHandler/JBoss.pm
  JMX::Jmx4Perl::Request:
    file: lib/JMX/Jmx4Perl/Request.pm
  JMX::Jmx4Perl::Response:
    file: lib/JMX/Jmx4Perl/Response.pm
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
