---
name: jmx4perl
version: 0.1
author:
  - Roland Huss (roland@cpan.org)
abstract: Easy JMX access to Java Applications
license: gpl
resources:
  license: http://www.gnu.org/licenses/old-licenses/gpl-1.0.txt
requires:
  Carp: 0
  Data::Dumper: 0
  Getopt::Long: 0
  JSON: 2.12
  LWP::UserAgent: 0
  Object::Tiny: 1.06
  Pod::Usage: 0
build_requires:
  Module::Build: 0
  Test: 0
  Test::More: 0
recommends:
  Nagios::Plugin: 0.27
provides:
  JMX::Jmx4Perl:
    file: lib/JMX/Jmx4Perl.pm
    version: 0.1
  JMX::Jmx4Perl::Agent:
    file: lib/JMX/Jmx4Perl/Agent.pm
  JMX::Jmx4Perl::Agent::UserAgent:
    file: lib/JMX/Jmx4Perl/Agent/UserAgent.pm
  JMX::Jmx4Perl::Request:
    file: lib/JMX/Jmx4Perl/Request.pm
  JMX::Jmx4Perl::Response:
    file: lib/JMX/Jmx4Perl/Response.pm
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
